 const doctors=[
  {
    name: "Dr.Bhartendu Kumar Varma",
    address: "Dr.Bhartendu Kumar Varma ,Embark Plaza, Noida Extension, Greater Noida, Uttar Pradesh 201009, India",
    phone: "+91 93113 05499",
    email: "info@ablasereye.com",
    lat: "28.6071114",
    lng: "77.4257536",
    url: "https://ablasereye.com/",
    country: "India",
    state: "Uttar Pradesh",
    city: "Noida",
    star_count: "5",
    rating_count: "25",
    zip: "201009",
    primary_category_name: "Ophthalmologists",
    category_name: "Eye care centers,Ophthalmology clinics,Ophthalmologists,Lasik surgeons,Surgeons,Hospitals,Doctors",
    
  },
  {
    name: "The Eye Foundation - Eye Hospital in Coonoor",
    address: "Nankem Hospital, near, YWCA Rd, Bedford, Coonoor, Tamil Nadu 643101, India",
    phone: "+91 93615 67426",
    email: "info@theeyefoundation.com",
    lat: "11.3448423",
    lng: "76.798277",
    url: "http://www.theeyefoundation.com/",
    country: "India",
    state: "Tamil Nadu",
    city: "Coonoor",
    star_count: "4.9",
    rating_count: "49",
    zip: "643101",
    primary_category_name: "Ophthalmologists",
    category_name: "Ophthalmologists",
   
  },
  {
    name: "Dr. Naveen Narendranath - Best Paediatric Ophthalmologist at Cloudnine Hospital, Chennai",
    address: "Raghav, Cloudnine Hospital, 54 Vijaya, Road, near Hyatt Regency, T. Nagar, Chennai, Tamil Nadu 600017, India",
    phone: "+91 99728 99728",
    email: "info@cloudninecare.com",
    lat: "13.0440339",
    lng: "80.2457467",
    url: "https://www.cloudninecare.com/doctors/dr-naveen-narendranath",
    country: "India",
    state: "Tamil Nadu",
    city: "Chennai",
    star_count: "4.5",
    rating_count: "2",
    zip: "600017",
    primary_category_name: "Ophthalmologists",
    category_name: "Abortion clinics,Birth control centers,Pediatricians,Ophthalmologists,Perinatal centers,Pregnancy care centers,Doctors,Birth centers,Women's health clinics",
   
  },
  {
    name: "Vision Eye Centre: Best Eye Hospital in Delhi | Best Eye Specialist in Delhi NCR",
    address: "Vision Eye Centre, 19, Siri Fort Rd, Sector 3, Sadiq Nagar, New Delhi, Delhi 110049, India",
    phone: "+91 88008 87084",
    email: "visioneyecentrehr@gmail.com",
    lat: "28.5548023",
    lng: "77.2254089",
    url: "http://www.visioneyecentre.com/",
    country: "India",
    state: "Delhi",
    city: "Delhi",
    star_count: "4.8",
    rating_count: "1195",
    zip: "110049",
    primary_category_name: "Ophthalmologists",
    category_name: "Eye care centers,Ophthalmologists,Hospitals",
    
  },
  {
    name: "PL Memorial Eye Clinic (Dr Sameer Kaushal) Affiliated with Comet Eye Care",
    address: "House No. 777, PL Memorial Eye Clinic, Sector 40, Gurugram, Haryana 122003, India",
    phone: "+91 78383 68568",
    email: "info@drsameerkaushal.com",
    lat: "28.448676",
    lng: "77.0559537",
    url: "http://drsameerkaushal.com/",
    country: "India",
    state: "Haryana",
    city: "Gurgaon",
    star_count: "4.6",
    rating_count: "61",
    zip: "122003",
    primary_category_name: "Ophthalmologists",
    category_name: "Eye care centers,Ophthalmologists,Ophthalmology clinics,Pediatric ophthalmologists,Lasik surgeons",
   
  },
  {
    name: "ASG Eye Hospital",
    address: "Tower, C, Infront of Hotel, Central Park, Nigotia, 1, City Center, Gwalior, Madhya Pradesh 474002, India",
    phone: "+91 88750 20785",
    email: "gwalior@asgeyehospital.com",
    lat: "26.2114599",
    lng: "78.1871297",
    url: "https://asgeyehospital.com/hospital/city-center-gwalior",
    country: "India",
    state: "Madhya Pradesh",
    city: "Gwalior",
    star_count: "4.9",
    rating_count: "1464",
    zip: "474002",
    primary_category_name: "Ophthalmologists",
    category_name: "Eye care centers,Ophthalmologists",
    
  },
  {
    name: "Dr A K Grover",
    address: "Vision Eye Centre, 19, Siri Fort Rd, Sector 3, Sadiq Nagar, New Delhi, Delhi 110049, India",
    phone: "+91 11 2588 2129",
    email: "visioneyecentrehr@gmail.com",
    lat: "28.5548963",
    lng: "77.2253963",
    url: "http://www.visioneyecentre.com/",
    country: "India",
    state: "Delhi",
    city: "Delhi",
    star_count: "3.9",
    rating_count: "69",
    zip: "110049",
    primary_category_name: "Ophthalmologists",
    category_name: "Ophthalmologists",
    
  },
  {
    name: "Eye7 Chaudhary Eye Centre",
    address: "Shipra Krishna Vista Plaza, 19, 1st Floor, Shipra Vista Plaza, Doctor Sushila Naiyar Marg, Ahinsa Khand 1, Indirapuram, Indirapuram, Dr Sushila Naiyar Marg, Ahinsa Khand 1, Indirapuram, Ghaziabad, Uttar Pradesh 201014, India",
    phone: "+91 11 4040 4070",
    email: "info@eye7.in",
    lat: "28.639529",
    lng: "77.37334",
    url: "http://www.eye7.in/",
    country: "India",
    state: "Uttar Pradesh",
    city: "Noida",
    star_count: "4.8",
    rating_count: "859",
    zip: "201014",
    primary_category_name: "Ophthalmologists",
    category_name: "Lasik surgeons,Pediatric ophthalmologists,Ophthalmologists,Eye care centers,Ophthalmology clinics",
    
  },
  {
    name: "Dr Somdutt Prasad",
    address: "C/o Divyadrishti, Dulal Apartment, 1st Floor 330, N.S.Road, Opposite Kali, Babu Bazar, Howrah, West Bengal 711101, India",
    phone: "+91 98305 07754",
    email: "prasad.retina@gmail.com",
    lat: "22.5811228",
    lng: "88.3258117",
    url: "http://www.somduttprasad.com/",
    country: "India",
    state: "West Bengal",
    city: "Kolkata",
    star_count: "5",
    rating_count: "2",
    zip: "711101",
    primary_category_name: "Ophthalmologists",
    category_name: "Ophthalmologists,Medical clinics,Surgeons",
    
  },
  {
    name: "Dr. Ashini Maniar",
    address: "Gokul Concorde, Ojas Eye Hospital - Jivala Pada Road Behind, off, Western Express Hwy, Dattani Park, Thakur Village, Kandivali East, Mumbai, Maharashtra 400101, India",
    phone: "+91 22 2886 9999",
    email: "info@ojaseyehospital.com",
    lat: "19.2143222",
    lng: "72.8689406",
    url: "https://www.ojaseyehospital.com/dr-ashini-maniar.html",
    country: "India",
    state: "Maharashtra",
    city: "Mumbai",
    star_count: "5",
    rating_count: "3",
    zip: "400101",
    primary_category_name: "Ophthalmologists",
    category_name: "Eye care centers,Lasik surgeons,Ophthalmology clinics,Ophthalmologists",
   
  },
  {
    name: "Dr. Surya Kant Jha | Eye Specialist, Cataract and LASIK Eye Surgeon in Delhi",
    address: "C-73, Ground Floor, near HDFC Bank, Shivalik Colony, Malviya Nagar, New Delhi, Delhi 110017, India",
    phone: "+91 93113 31966",
    email: "eterna.clinics@gmail.com",
    lat: "28.540753",
    lng: "77.2123092",
    url: "https://suryakantjhaeyesurgeon.com/",
    country: "India",
    state: "Delhi",
    city: "Delhi",
    star_count: "5",
    rating_count: "58",
    zip: "110017",
    primary_category_name: "Ophthalmologists",
    category_name: "Eye care centers,Medical clinics,Doctors,Ophthalmology clinics,Ophthalmologists",
   
  },
  {
    name: "Vision Eye Centre: Best Eye Centre in Delhi | Best Eye Doctor in Delhi",
    address: "12/27, W Patel Nagar Rd, near Arya Samaj Mandir, Sector 14, Block 26, East Patel Nagar, Patel Nagar, New Delhi, Delhi, 110008, India",
    phone: "+91 88008 87084",
    email: "visioneyecentrehr@gmail.com",
    lat: "28.648354",
    lng: "77.1679445",
    url: "http://www.visioneyecentre.com/",
    country: "India",
    state: "Delhi",
    city: "Delhi",
    star_count: "4.9",
    rating_count: "723",
    zip: "110008",
    primary_category_name: "Ophthalmologists",
    category_name: "Ophthalmology clinics,Lasik surgeons,Ophthalmologists,Hospitals,Eye care centers",
  
  },
  {
    name: "Precise Eye 1 Eye Care",
    address: "Packanadathil Building, near Union Bank, Pandalam, Kerala 689501, India",
    phone: "+91 4734 298 555",
    email: "mail@preciseeye.in",
    lat: "9.225457",
    lng: "76.6797718",
    url: "https://www.preciseeye.in/",
    country: "India",
    state: "Kerala",
    city: "Kochi",
    star_count: "4.7",
    rating_count: "198",
    zip: "689501",
    primary_category_name: "Ophthalmologists",
    category_name: "Eye care centers,Ophthalmologists,Pediatric ophthalmologists,Ophthalmology clinics,Lasik surgeons,Hospitals,Optometrists",
  
  },
  {
    name: "Dr. Sanjay Chaudhary",
    address: "4802/24, Bharat Ram Rd, Daryaganj, New Delhi, Delhi, 110002, India",
    phone: "+91 96437 78899",
    email: "info@eye7.in",
    lat: "28.6419447",
    lng: "77.2436547",
    url: "http://www.eye7.in/",
    country: "India",
    state: "Delhi",
    city: "Delhi",
    star_count: "3.9",
    rating_count: "76",
    zip: "110002",
    primary_category_name: "Ophthalmologists",
    category_name: "Ophthalmologists",

  },
  {
    name: "ASG Eye Hospital",
    address: "Plot no. 7&8, Mandore Rd, Manji ka Hatha, Paota, Jodhpur, Rajasthan 342003, India",
    phone: "+91 88750 20785",
    email: "jodhpur@asgeyehospital.com",
    lat: "26.299076",
    lng: "73.03881",
    url: "https://asgeyehospital.com/hospital/paota-jodhpur",
    country: "India",
    state: "Rajasthan",
    city: "Jodhpur",
    star_count: "4.8",
    rating_count: "3441",
    zip: "342003",
    primary_category_name: "Ophthalmologists",
    category_name: "Ophthalmologists,Eye care centers",

  },
  {
    name: "A B Laser Eye Centre- A Super Speciality Eye Hospital",
    address: "Embark Plaza, Gaur City 1, Sector 4, Noida, Ghaziabad, Uttar Pradesh 201009, India",
    phone: "+91 93113 05500",
    email: "info@ablasereye.com",
    lat: "28.6076514",
    lng: "77.4256341",
    url: "https://ablasereye.com/",
    country: "India",
    state: "Uttar Pradesh",
    city: "Noida",
    star_count: "5",
    rating_count: "1181",
    zip: "201009",
    primary_category_name: "Ophthalmologists",
    category_name: "Lasik surgeons,Pediatric ophthalmologists,Pediatric surgeons,Ophthalmologists,Eye care centers,Surgeons,Hospitals,Doctors",

  },
  {
    name: "ASG Eye Care",
    address: "22/5, Haridwar Rd, opp. Uttarakhand State Roadways Workshop, Race Course, Dehradun, Uttarakhand 248001, India",
    phone: "+91 1800 1200",
    email: "dehradun@asgeyehospital.com",
    lat: "30.3146153",
    lng: "78.044647",
    url: "https://asgeyehospital.com/hospital/race-course-dehradun",
    country: "India",
    state: "Uttarakhand",
    city: "Dehradun",
    star_count: "5",
    rating_count: "140",
    zip: "248001",
    primary_category_name: "Ophthalmologists",
    category_name: "Eye care centers,Ophthalmologists",

  },
  {
    name: "Niteen Dedhia",
    address: "Ojas Eye Hospital - Jivala pada Road, Near Gokul Concord Tower, Thakur Village Road, Off Western Express Highway, Kandivali East, Mumbai, Maharashtra 400101, India",
    phone: "+91 70452 20120",
    email: "info@ojaseyehospital.com",
    lat: "19.214378",
    lng: "72.869718",
    url: "https://www.ojaseyehospital.com/",
    country: "India",
    state: "Maharashtra",
    city: "Mumbai",
    star_count: "4.3",
    rating_count: "33",
    zip: "400101",
    primary_category_name: "Ophthalmologists",
    category_name: "Ophthalmologists",

  },
  {
    name: "Dr Pratyush Ranjan (डॉ प्रत्यूष रंजन)",
    address: "ASG Eye Hospital Ground Floor, Corporate Plaza On, main, Rathyatra - Mahmoorganj Rd, Mahmoorganj, Varanasi, Uttar Pradesh 221010, India",
    phone: "+91 98079 88146",
    email: "filler@godaddy.com",
    lat: "25.3060726",
    lng: "82.9845078",
    url: "https://drcdeye.com/",
    country: "India",
    state: "Uttar Pradesh",
    city: "Varanasi",
    star_count: "4.9",
    rating_count: "2447",
    zip: "221010",
    primary_category_name: "Ophthalmologists",
    category_name: "Ophthalmologists",

  },
  {
    name: "ASG Eye Hospital",
    address: "Embassy Tower, Plot No. 9 / 1 / 3, Mahatma Gandhi Rd, Near Treasure Island, First, Mall, Indore, Madhya Pradesh 452001, India",
    phone: "+91 88750 20785",
    email: "indore@asgeyehospital.com",
    lat: "22.7218681",
    lng: "75.8796019",
    url: "https://asgeyehospital.com/hospital/mahatma-gandhi-road-indore",
    country: "India",
    state: "Madhya Pradesh",
    city: "Indore",
    star_count: "4.9",
    rating_count: "5575",
    zip: "452001",
    primary_category_name: "Ophthalmologists",
    category_name: "Ophthalmologists,Eye care centers",

  },
  {
    name: "108 Eye & Health Centre",
    address: "E 108, E Block, Sector 50, Noida, Uttar Pradesh 201301, India",
    phone: "+91 90158 21616",
    email: "info@108eye.com",
    lat: "28.5721581",
    lng: "77.3691918",
    url: "http://www.108eye.com/",
    country: "India",
    state: "Uttar Pradesh",
    city: "Noida",
    star_count: "5",
    rating_count: "54",
    zip: "201301",
    primary_category_name: "Ophthalmologists",
    category_name: "Ophthalmologists",

  },
  {
    name: "Trinity Super Speciality Eye Hospital, Thrissur",
    address: "Aswini Junction, Kovilakathumpadam, Kodungallur - Shornur Rd, Vasanth Nagar, Patturaikkal, Thrissur, Kerala 680020, India",
    phone: "+91 1800 4255 7799",
    email: "admin@trinityeyehospital.com",
    lat: "10.5362518",
    lng: "76.2149712",
    url: "https://www.trinityeyehospital.com/",
    country: "India",
    state: "Kerala",
    city: "Thrissur",
    star_count: "4.9",
    rating_count: "419",
    zip: "680020",
    primary_category_name: "Ophthalmologists",
    category_name: "Optometrists,Eye care centers,Lasik surgeons,Ophthalmology clinics,Pediatric ophthalmologists,Opticians,Ophthalmologists,Doctors",

  },
  {
    name: "Sri Eye Care Speciality Eye Hospital",
    address: "HBR Layout 2nd Block, Stage 1, HBR Layout, Bengaluru, Karnataka 560043, India",
    phone: "+91 89048 23434",
    email: "info@srieye.care",
    lat: "13.0196865",
    lng: "77.6285443",
    url: "https://www.srieyecarehospital.com/",
    country: "India",
    state: "Karnataka",
    city: "Bengaluru",
    star_count: "4.8",
    rating_count: "205",
    zip: "560043",
    primary_category_name: "Ophthalmologists",
    category_name: "Eye care centers,Pediatric ophthalmologists,Lasik surgeons,Ophthalmology clinics,Optometrists,Ophthalmologists,Opticians,Hospitals",

  },
  {
    name: "Delhi Eye Care: Best Eye Hospital in Patel Nagar, Delhi, India",
    address: "4/21, Balraj Khanna Marg, near Amrapali Hotel, Block 4, East Patel Nagar, Patel Nagar, New Delhi, Delhi 110008, India",
    phone: "+91 11 4562 9416",
    email: "delhieyecarepatelnagar@gmail.com",
    lat: "28.6431372",
    lng: "77.1737847",
    url: "http://www.delhieyecare.com/",
    country: "India",
    state: "Delhi",
    city: "Delhi",
    star_count: "4.8",
    rating_count: "308",
    zip: "110008",
    primary_category_name: "Ophthalmologists",
    category_name: "Ophthalmologists,Opticians,Lasik surgeons,Pediatric ophthalmologists,Ophthalmology clinics,Eye care centers",

  },
  {
    name: "ASG Eye Hospital",
    address: "70/2, Deshpran Sasmal Rd, Tollygunge Phari, Tollygunge, Kolkata, West Bengal 700033, India",
    phone: "+91 88750 20785",
    email: "kolkatatolly@asgeyehospital.com",
    lat: "22.5023786",
    lng: "88.3448426",
    url: "https://asgeyehospital.com/hospital/tollygunge-kolkata",
    country: "India",
    state: "West Bengal",
    city: "Kolkata",
    star_count: "4.9",
    rating_count: "822",
    zip: "700033",
    primary_category_name: "Ophthalmologists",
    category_name: "Eye care centers,Ophthalmologists",

  },
  {
    name: "Dr Somdutt Prasad",
    address: "No. A, Amri Medical Centre, C/o, Southern Ave, opp. Lake Stadium, lake Terrace, Ballygunge, Kolkata, West Bengal 700029, India",
    phone: "+91 98305 07754",
    email: "prasad.retina@gmail.com",
    lat: "22.5133385",
    lng: "88.352681",
    url: "http://www.somduttprasad.com/",
    country: "India",
    state: "West Bengal",
    city: "Kolkata",
    star_count: "3.2",
    rating_count: "6",
    zip: "700029",
    primary_category_name: "Ophthalmologists",
    category_name: "Ophthalmologists,Surgeons,Hospitals,Medical clinics",

  },
  {
    name: "Dr. Rahil Chaudhary",
    address: "34, Ring Rd, Block P, Lajpat Nagar IV, Lajpat Nagar 4, New Delhi, Delhi 110024, India",
    phone: "+91 96437 78899",
    email: "info@eye7.in",
    lat: "28.5650894",
    lng: "77.2490026",
    url: "https://www.eye7.in/eye-specialists/dr-rahil-chaudhary/",
    country: "India",
    state: "Delhi",
    city: "Delhi",
    star_count: "4.7",
    rating_count: "422",
    zip: "110024",
    primary_category_name: "Ophthalmologists",
    category_name: "Ophthalmologists",

  },
  {
    name: "ASG Eye Hospital",
    address: "403/1, Alcove Gloria, Above Big Bazaar, Dakshindari Road, VIP Rd, near Lake Town, Sreebhumi, Kolkata, West Bengal 700048, India",
    phone: "+91 88750 20785",
    email: "kolkata@asgeyehospital.com",
    lat: "22.5977439",
    lng: "88.4019466",
    url: "https://asgeyehospital.com/hospital/sreebhumi-kolkata/",
    country: "India",
    state: "West Bengal",
    city: "Kolkata",
    star_count: "4.7",
    rating_count: "2177",
    zip: "700048",
    primary_category_name: "Ophthalmologists",
    category_name: "Ophthalmologists,Eye care centers",

  },
  {
    name: "Grewal Eye Institute",
    address: "168-169, Madhya Marg, 9C, Sector 9, Chandigarh, 160009, India",
    phone: "+91 172 505 6969",
    email: "info@gei.co.in",
    lat: "30.7417631",
    lng: "76.7909316",
    url: "http://www.gei.co.in/",
    country: "India",
    state: "Chandigarh",
    city: "Chandigarh",
    star_count: "4.3",
    rating_count: "1317",
    zip: "160009",
    primary_category_name: "Ophthalmologists",
    category_name: "Optometrists,Pediatric surgeons,Ophthalmology clinics,Lasik surgeons,Eye care centers,Ophthalmologists",

  },
  {
    name: "ASG Eye Hospital",
    address: "124, Napier Town landmark:, near, Shastri Bridge, Jabalpur, Madhya Pradesh 482001, India",
    phone: "+91 88750 20785",
    email: "jabalpur@asgeyehospital.com",
    lat: "23.1592086",
    lng: "79.9303712",
    url: "https://asgeyehospital.com/hospital/shastri-bridge-jabalpur",
    country: "India",
    state: "Madhya Pradesh",
    city: "Jabalpur",
    star_count: "4.9",
    rating_count: "5293",
    zip: "482001",
    primary_category_name: "Ophthalmologists",
    category_name: "Eye care centers,Ophthalmologists",
  
  }

]
export default doctors;